# Generated by Django 4.0.2 on 2022-02-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('meal', models.TextField(choices=[('Cheeseburger', 'Cheeseburger'), ('Hot dog', 'Hot dog'), ('Pizza', 'Pizza'), ('T-Bone', 'T-Bone'), ('French fries', 'French fries'), ('Salmon tartar', 'Salmon tartar')], max_length=20)),
            ],
        ),
    ]
